services:

  Kachuru\Vindinium\Bot\ScoredBoardTile:
    class: Kachuru\Vindinium\Bot\ScoredBoardTile
    arguments:
      - Kachuru\Vindinium\Game\BoardTile
      - Kachuru\Vindinium\Bot\BoardTileScore

  Kachuru\Vindinium\Client:
    arguments:
      - "%vindinium.server%"
      - "%vindinium.key%"

  Kachuru\Vindinium\Bot\BotFactory:
    calls:
      - method: addBot
        arguments:
          - '@Kachuru\Vindinium\Bot\BasicBot'
      - method: addBot
        arguments:
          - '@Kachuru\Vindinium\Bot\CleverBot'
