services:

  Kachuru\Vindinium\Bot\ScoredBoardTile:
    class: Kachuru\Vindinium\Bot\ScoredBoardTile
    arguments:
      - Kachuru\Vindinium\Game\BoardTile
      - Kachuru\Vindinium\Bot\BoardTileScore

  Kachuru\Vindinium\Bot\BotFactory:
    calls:
      - method: addBot
        arguments:
          - '@Kachuru\Vindinium\Bot\RandomBot'
      - method: addBot
        arguments:
          - '@Kachuru\Vindinium\Bot\AimlessBot'
      - method: addBot
        arguments:
          - '@Kachuru\Vindinium\Bot\BasicBot'
      - method: addBot
        arguments:
          - '@Kachuru\Vindinium\Bot\CleverBot'

  Kachuru\Vindinium\Command\TrainCommand:
    autowire: "true"
    tags:
      tag:
        name: "vindinium-bot.console.command"
        configurator: 'Kachuru\Vindinium\VindiniumCommandConfigurator'

  Kachuru\Vindinium\Command\ArenaCommand:
    autowire: "true"
    tags:
      tag:
        name: "vindinium-bot.console.command"
        configurator: 'Kachuru\Vindinium\VindiniumCommandConfigurator'

  Kachuru\Vindinium\Display\DisplayFactory:
    calls:
      - method: addDisplay
        arguments:
          - '@Kachuru\Vindinium\Display\StandardDisplay'
      - method: addDisplay
        arguments:
          - '@Kachuru\Vindinium\Display\EnhancedMapDisplay'

  Kachuru\Vindinium\VindiniumClient:
    arguments:
      - "%vindinium.server%"
      - "%vindinium.key%"
